// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEhcsO5Ilyj6_d2j3ID327c8QgQ5Z0hSw',
    appId: '1:409351809932:web:b164a8c820648d87e084a9',
    messagingSenderId: '409351809932',
    projectId: 'live-vote-f21f8',
    authDomain: 'live-vote-f21f8.firebaseapp.com',
    databaseURL: 'https://live-vote-f21f8-default-rtdb.firebaseio.com',
    storageBucket: 'live-vote-f21f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4XjWEVQ7vFVvejB878n2847Kanzio6mk',
    appId: '1:409351809932:android:0744088bcece64cae084a9',
    messagingSenderId: '409351809932',
    projectId: 'live-vote-f21f8',
    databaseURL: 'https://live-vote-f21f8-default-rtdb.firebaseio.com',
    storageBucket: 'live-vote-f21f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrBHkpVYAHvwW2dIGesOTIgXpm23FvYa0',
    appId: '1:409351809932:ios:2c3274338cec928be084a9',
    messagingSenderId: '409351809932',
    projectId: 'live-vote-f21f8',
    databaseURL: 'https://live-vote-f21f8-default-rtdb.firebaseio.com',
    storageBucket: 'live-vote-f21f8.appspot.com',
    iosBundleId: 'com.example.liveVote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrBHkpVYAHvwW2dIGesOTIgXpm23FvYa0',
    appId: '1:409351809932:ios:b98aca0d209c5134e084a9',
    messagingSenderId: '409351809932',
    projectId: 'live-vote-f21f8',
    databaseURL: 'https://live-vote-f21f8-default-rtdb.firebaseio.com',
    storageBucket: 'live-vote-f21f8.appspot.com',
    iosBundleId: 'com.example.liveVote.RunnerTests',
  );
}
